// Import the service to be tested
const ecpayService = require('../services/ecpayService');

// Mock the ECPay SDK
const mockAioCheckOutAll = jest.fn().mockReturnValue('<mocked_ecpay_html>');
const mockGenerateCheckMacValue = jest.fn();

jest.mock('ecpay_aio_nodejs', () => {
  // This is the mock constructor for 'new ecpay_payment(options)'
  return jest.fn().mockImplementation(() => ({
    payment_client: {
      aio_check_out_all: mockAioCheckOutAll,
      generate_check_mac_value: mockGenerateCheckMacValue
    }
  }));
});

// Mock environment variables - ECPay SDK and service might try to load them via dotenv
// For tests, we can set them directly if not already set by a test setup file.
// These are particularly important for the manual fallback in verifyReturnPayload.
const originalEnv = process.env;

describe('ecpayService', () => {
  beforeEach(() => {
    // Reset mocks before each test
    mockAioCheckOutAll.mockClear();
    mockGenerateCheckMacValue.mockClear();
    
    // Reset process.env to a copy of the original state
    process.env = { ...originalEnv };
    // Define essential ECPay credentials for tests that might reach manual checksum
    process.env.MERCHANTID = '2000132'; // Test MerchantID
    process.env.HASHKEY = '5294y06JbISpM5x9'; // Test HashKey
    process.env.HASHIV = 'v77hoKGq4kWxNNIS'; // Test HashIV
    process.env.HOST = 'http://localhost:3000'; // Test Host
  });

  afterAll(() => {
    // Restore original environment variables
    process.env = originalEnv;
  });

  describe('initiateCheckout', () => {
    it('should call ECPay SDK aio_check_out_all and return its HTML', () => {
      const checkoutData = {
        orderId: 'testOrder123',
        totalAmount: '150',
        description: 'Test Description',
        items: 'Test Item'
      };
      const html = ecpayService.initiateCheckout(checkoutData);

      expect(html).toBe('<mocked_ecpay_html>');
      expect(mockAioCheckOutAll).toHaveBeenCalledTimes(1);
      // We can also check the arguments passed to aio_check_out_all if needed
      expect(mockAioCheckOutAll).toHaveBeenCalledWith(
        expect.objectContaining({
          TotalAmount: '150',
          TradeDesc: 'Test Description',
          ItemName: 'Test Item',
          MerchantTradeNo: expect.any(String), // Generated by uuid, so we check for type
          MerchantTradeDate: expect.any(String), // Generated date string
          ReturnURL: 'http://localhost:3000/return'
        })
      );
    });

    it('should throw an error if ECPay SDK fails during HTML generation', () => {
        mockAioCheckOutAll.mockImplementationOnce(() => {
          throw new Error('SDK Internal Error');
        });
  
        const checkoutData = { /* ... */ };
        expect(() => {
          ecpayService.initiateCheckout(checkoutData);
        }).toThrow('ECPay HTML generation failed. Details: SDK Internal Error');
      });
  });

  describe('verifyReturnPayload', () => {
    const baseMockPayload = {
      ItemName: "Test Product",
      MerchantID: "2000132",
      MerchantTradeNo: "testUUID12345", // Matches MerchantID from .env for consistency
      PaymentDate: "2024/07/30 10:09:30",
      PaymentType: "Credit_CreditCard",
      PaymentTypeChargeFee: "1",
      RtnCode: "1", // Assuming success for this field in successful payment
      RtnMsg: "交易成功",
      TradeAmt: "150",
      TradeDate: "2024/07/30 10:08:30",
      TradeNo: "2407301009302107",
      // CheckMacValue will be added per test case
    };

    it('should return success if SDK CheckMacValue matches', () => {
      const mockPayload = {
        ...baseMockPayload,
        CheckMacValue: "SDK_MATCHING_MAC"
      };
      mockGenerateCheckMacValue.mockReturnValue("SDK_MATCHING_MAC");

      const result = ecpayService.verifyReturnPayload(mockPayload);
      expect(result.success).toBe(true);
      expect(result.merchantTradeNo).toBe("testUUID12345");
      expect(mockGenerateCheckMacValue).toHaveBeenCalledWith(mockPayload);
    });

    it('should return error if CheckMacValue is missing', () => {
      const mockPayload = { ...baseMockPayload }; // No CheckMacValue
      const result = ecpayService.verifyReturnPayload(mockPayload);
      expect(result.success).toBe(false);
      expect(result.error).toBe("Missing CheckMacValue");
    });

    it('should return error if SDK CheckMacValue mismatches', () => {
      const mockPayload = {
        ...baseMockPayload,
        CheckMacValue: "RECEIVED_MAC_DIFFERENT"
      };
      mockGenerateCheckMacValue.mockReturnValue("CALCULATED_MAC_BY_SDK");

      const result = ecpayService.verifyReturnPayload(mockPayload);
      expect(result.success).toBe(false);
      expect(result.error).toBe("Checksum mismatch");
      expect(result.receivedMac).toBe("RECEIVED_MAC_DIFFERENT");
      expect(result.calculatedMac).toBe("CALCULATED_MAC_BY_SDK");
    });

    it('should succeed with manual verification if SDK fails and manual MAC matches', () => {
      // This test relies on the actual crypto logic for manual calculation.
      // We need to provide a payload that, when manually calculated, yields a known MAC.
      // The HASHKEY and HASHIV are set in beforeEach from process.env.
      
      // Simulate SDK failure
      mockGenerateCheckMacValue.mockImplementation(() => {
        throw new Error("SDK checksum generation failed");
      });

      // Construct a payload and pre-calculate its *correct* manual CheckMacValue
      // For simplicity, we'll use a known simple payload.
      // Note: The actual manual calculation is complex. For a unit test, you might
      // further mock the crypto functions if you want to avoid testing Node's crypto.
      // However, here we test the service's manual path integration.
      
      const payloadForManual = {
        MerchantID: process.env.MERCHANTID, // Use the one from env
        MerchantTradeNo: "manualtest123",
        TotalAmount: "100",
        TradeDesc: "Manual Test",
        ItemName: "ItemManual",
        RtnCode: "1",
        // IMPORTANT: The actual CheckMacValue must be calculated based on *this* payload
        // and the HASHKEY/HASHIV from the test environment.
        // This is the hardest part to get right in a static test definition without running the code.
        // Let's assume a hypothetical correct MAC for this specific payload and env vars.
        // This usually means running the manual calculation once to get the expected value.
        // For this example, I'll use a placeholder. A real test would need the actual value.
        CheckMacValue: "HYPOTHETICAL_CORRECT_MANUAL_MAC" 
      };
      
      // To make this test pass, we need to make `HYPOTHETICAL_CORRECT_MANUAL_MAC` the actual
      // result of the manual calculation based on `payloadForManual` (without CheckMacValue field)
      // and the HASHKEY/HASHIV set in `beforeEach`.
      // Let's compute it:
      // String: HashKey=5294y06JbISpM5x9&ItemName=ItemManual&MerchantID=2000132&MerchantTradeNo=manualtest123&RtnCode=1&TotalAmount=100&TradeDesc=Manual Test&HashIV=v77hoKGq4kWxNNIS
      // Encoded+Lower: hashkey%3d5294y06jbispn5x9%26itemname%3ditemmanual%26merchantid%3d2000132%26merchanttradeno%3dmanualtest123%26rtncode%3d1%26totalamount%3d100%26tradedesc%3dmanual%20test%26hashiv%3dv77hokgq4kwxnnis
      // SHA256: Let's assume this results in 'PRECALCULATED_MANUAL_MAC_FOR_TEST'
      // For this example, I will hardcode an expected value. In a real scenario, this value
      // would be derived from running the manual calculation logic separately with the test data.
      // A more robust way would be to mock `crypto.createHash` if the goal is not to test crypto itself.
      // Given the constraints, I'll set a plausible MAC.
      
      // Let's adjust the payload to make it simple and calculate its MAC.
      // Parameters sorted: HashKey=VALUE&A=1&B=2&HashIV=VALUE
      const crypto = require('crypto');
      const testPayload = { MerchantTradeNo: "ORDER1", RtnCode: "1", TradeAmt: "50" };
      let checkString = `HashKey=${process.env.HASHKEY}`;
      Object.keys(testPayload).sort((a,b) => a.toLowerCase().localeCompare(b.toLowerCase())).forEach(key => {
        checkString += `&${key}=${testPayload[key]}`;
      });
      checkString += `&HashIV=${process.env.HASHIV}`;
      let urlEncodedString = encodeURIComponent(checkString)
        .replace(/%20/g, "+").replace(/%2d/g, "-").replace(/%5f/g, "_")
        .replace(/%2e/g, ".").replace(/%21/g, "!").replace(/%2a/g, "*")
        .replace(/%28/g, "(").replace(/%29/g, ")");
      let lowerCaseString = urlEncodedString.toLowerCase();
      const sha256 = crypto.createHash('sha256');
      sha256.update(lowerCaseString);
      const correctManualMac = sha256.digest('hex').toUpperCase();

      const payloadWithCorrectManualMac = {
        ...testPayload,
        CheckMacValue: correctManualMac
      };
      
      const result = ecpayService.verifyReturnPayload(payloadWithCorrectManualMac);
      expect(result.success).toBe(true);
      expect(result.merchantTradeNo).toBe("ORDER1");
      expect(mockGenerateCheckMacValue).toHaveBeenCalledTimes(1); // SDK tried and failed
    });

    it('should return error if SDK fails and manual MAC mismatches', () => {
        mockGenerateCheckMacValue.mockImplementation(() => {
          throw new Error("SDK checksum generation failed");
        });
  
        const payloadWithIncorrectManualMac = {
          MerchantTradeNo: "ORDER2", RtnCode: "1", TradeAmt: "70",
          CheckMacValue: "INCORRECT_MANUAL_MAC_FOR_SURE"
        };
        
        const result = ecpayService.verifyReturnPayload(payloadWithIncorrectManualMac);
        expect(result.success).toBe(false);
        expect(result.error).toBe("Checksum mismatch");
        expect(result.receivedMac).toBe("INCORRECT_MANUAL_MAC_FOR_SURE");
        // result.calculatedMac would be the one from the manual calculation here
        expect(result.calculatedMac).not.toBe("INCORRECT_MANUAL_MAC_FOR_SURE"); 
      });

      it('should return error if HASHKEY is missing for manual calculation', () => {
        delete process.env.HASHKEY; // Remove HASHKEY for this test
        mockGenerateCheckMacValue.mockImplementation(() => {
          throw new Error("SDK checksum generation failed");
        });
  
        const mockPayload = { ...baseMockPayload, CheckMacValue: "ANYMAC" };
        const result = ecpayService.verifyReturnPayload(mockPayload);
        expect(result.success).toBe(false);
        expect(result.error).toBe("Server configuration error: Missing HashKey/HashIV");
      });
  });
});
